blank_issues_enabled: false
contact_links:
  - name: 🤔 Question 
    url: https://github.com/Firedogs2x/Houdoku-2/discussions/new
    about: Ask a question about Houdoku 
  - name: 🖥️ Houdoku website
    url: https://houdoku.org
    about: Documentation for using Houdoku
